### ISSUE TITLE
java.lang.NoSuchFieldException: locale

### ISSUE THREAD

**Issue by DexterSK** [metamechanists/Quaptics#10]
1.20.2

`[04:08:06 INFO]: [Quaptics] [ACF] Can't read players locale, you will be unable to automatically detect players language. Only Bukkit 1.7+ is supported for this.
[04:08:06 INFO]: [Quaptics] [ACF] java.lang.NoSuchFieldException: locale
[04:08:06 INFO]: [Quaptics] [ACF]       at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
[04:08:06 INFO]: [Quaptics] [ACF]       at SlimefunQuaptics.jar//co.aikar.commands.BukkitCommandManager.readPlayerLocale(BukkitCommandManager.java:324)
[04:08:06 INFO]: [Quaptics] [ACF]       at SlimefunQuaptics.jar//co.aikar.commands.ACFBukkitListener.onPlayerJoin(ACFBukkitListener.java:57)
[04:08:06 INFO]: [Quaptics] [ACF]       at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40)
[04:08:06 INFO]: [Quaptics] [ACF]       at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[04:08:06 INFO]: [Quaptics] [ACF]       at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[04:08:06 INFO]: [Quaptics] [ACF]       at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[04:08:06 INFO]: [Quaptics] [ACF]       at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[04:08:06 INFO]: [Quaptics] [ACF]       at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[04:08:06 INFO]: [Quaptics] [ACF]       at net.minecraft.server.players.PlayerList.a(PlayerList.java:325)
[04:08:06 INFO]: [Quaptics] [ACF]       at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.a(ServerConfigurationPacketListenerImpl.java:130)
[04:08:06 INFO]: [Quaptics] [ACF]       at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:18)
[04:08:06 INFO]: [Quaptics] [ACF]       at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9)
[04:08:06 INFO]: [Quaptics] [ACF]       at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:53)
[04:08:06 INFO]: [Quaptics] [ACF]       at net.minecraft.server.TickTask.run(TickTask.java:18)
[04:08:06 INFO]: [Quaptics] [ACF]       at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[04:08:06 INFO]: [Quaptics] [ACF]       at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[04:08:06 INFO]: [Quaptics] [ACF]       at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1351)
[04:08:06 INFO]: [Quaptics] [ACF]       at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)
[04:08:06 INFO]: [Quaptics] [ACF]       at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[04:08:06 INFO]: [Quaptics] [ACF]       at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1328)
[04:08:06 INFO]: [Quaptics] [ACF]       at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1321)
[04:08:06 INFO]: [Quaptics] [ACF]       at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[04:08:06 INFO]: [Quaptics] [ACF]       at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1299)
[04:08:06 INFO]: [Quaptics] [ACF]       at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1187)
[04:08:06 INFO]: [Quaptics] [ACF]       at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[04:08:06 INFO]: [Quaptics] [ACF]       at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by LordIdra** [comment]
What server software are you using? Also could you run /sf versions and send a screenshot of the whole output please? Thanks

**Comment by DexterSK** [comment]
Current: git-Purpur-2083 (MC: 1.20.2)*

`[13:29:10 INFO]: This Server uses the following setup of Slimefun:
[13:29:10 INFO]: Purpur git-Purpur-2083 (MC: 1.20.2)
[13:29:10 INFO]: Slimefun DEV - 1104 (git c977454e)
[13:29:10 INFO]: Metrics-Module #29
[13:29:10 INFO]: Java 17
[13:29:10 INFO]: 
[13:29:10 INFO]: Installed Addons: (44)
[13:29:10 INFO]:   GlobalWarming vDEV - 11 (git 73ff77d4)
[13:29:10 INFO]:   Networks vDEV - 50 (git 3de3c9d6)
[13:29:10 INFO]:   ShopGUIPlus v1.81.1
[13:29:10 INFO]:   ExtraTools vDEV - 36 (git 922c0324)
[13:29:10 INFO]:   FoxyMachines vDEV - 67 (git 0028aa93)
[13:29:10 INFO]:   Quaptics vDEV - 4 (git cbc2e78e)
[13:29:10 INFO]:   SlimefunOreChunks vDEV - 15 (git 2520cb23)
[13:29:10 INFO]:   FNAmplifications vDEV - 93 (git 7bc01100)
[13:29:10 INFO]:   Bump vBuild 32 zh-CN(SlimefunGuguProject) (git 4923d02)
[13:29:10 INFO]:   CreativeManager v1.31.1
[13:29:10 INFO]:   DynaTech vDEV - 201 (git 0feb2ee0)
[13:29:10 INFO]:   AdvancedEnchantments v9.4.16
[13:29:10 INFO]:   ExtraGear vDEV - 13 (git c62047e2)
[13:29:10 INFO]:   SlimeHUD vDEV - 11 (git b6dc2d53)
[13:29:10 INFO]:   InfinityExpansion vDEV - 144 (git 9da37202)
[13:29:10 INFO]:   Supreme vDEV - 29 (git f9e70053)
[13:29:10 INFO]:   SFCalc vDEV - 37 (git dfc0fc41)
[13:29:10 INFO]:   Wildernether vDEV - 5 (git 5be3da69)
[13:29:10 INFO]:   CompressionCraft vDEV - 25 (git dbca94b8)
[13:29:10 INFO]:   UltimateGenerators v1.0.8
[13:29:10 INFO]:   ExtraHeads vDEV - 25 (git 8c29f73a)
[13:29:10 INFO]:   SlimyTreeTaps vDEV - 20 (git 963f0383)
[13:29:10 INFO]:   FlowerPower vDEV - 16 (git 5a38d1c6)
[13:29:10 INFO]:   TranscEndence vDEV - 41 (git 98d7d47e)
[13:29:10 INFO]:   CMI v9.6.7.0
[13:29:10 INFO]:   FluffyMachines vDEV - 132 (git ccf029ba)
[13:29:10 INFO]:   GeneticChickengineering v1.0
[13:29:10 INFO]:   ItemsAdder v3.6.2-beta-r2
[13:29:10 INFO]:   Brewery v3.1.1
[13:29:10 INFO]:   Nexcavate v1.0
[13:29:10 INFO]:   DyedBackpacks vDEV - 17 (git 8b329e96)
[13:29:10 INFO]:   AdvancedChests v27.8
[13:29:10 INFO]:   Residence v5.1.4.0
[13:29:10 INFO]:   EcoPower vDEV - 5 (git 5c1ecd68)
[13:29:10 INFO]:   SlimefunLuckyBlocks vDEV - 36 (git 60f0c8dc)
[13:29:10 INFO]:   ExoticGarden vDEV - 78 (git 7f9a5f63)
[13:29:10 INFO]:   HeadLimiter vDEV - 14 (git 0a02e2fd)
[13:29:10 INFO]:   DankTech2 vDEV - 9 (git aa6c2209)
[13:29:10 INFO]:   Liquid vDEV - 14 (git 0f5346bf)
[13:29:10 INFO]:   LiteXpansion vDEV 189 (git b2d7c)
[13:29:10 INFO]:   SimpleUtils vDEV - 15 (git 4250fd5e)
[13:29:10 INFO]:   ElementManipulation vDEV - 28 (git 2b469991)
[13:29:10 INFO]:   TinkerTools v2.1.0
[13:29:10 INFO]:   ChocoHills v1.0`

**Comment by LordIdra** [comment]
Bug with one of our dependencies, should hopefully be fixed next release. Thanks for the report.
